# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Login to Azure ACR
      run: |
          az login --service-principal --username ${{ secrets.ACR_CREDENTIALS }} --password ${{ secrets.ACR_CREDENTIALS }} --tenant ${{ secrets.ACR_TENANT_ID }}
          az acr login --name winctrcr
    - name: Build and push Docker image
      run: |
        docker build . -f Dockerfile -t winctrcr.azurecr.io/murty/weatherapi:latest
        docker push winctrcr.azurecr.io/murty/weatherapi:latest
